import type {Scene} from './types';

export const scenes: Scene[] = [
    {
        id: 1,
        title: '2019-2021 · 懵懂又单纯',
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        items: [
            {
                id: 1,
                x: 15,
                y: 25,
                emoji: '💝',
                memory: {
                    id: 1,
                    year: '2019',
                    title: '回忆标题1',
                    description: '这里是回忆描述...(替换为真实回忆)',
                    image: '/2019-2021/photo1.JPG',
                },
            },
            {
                id: 2,
                x: 45,
                y: 30,
                emoji: '🎬',
                memory: {
                    id: 2,
                    year: '2019',
                    title: '回忆标题2',
                    description: '这里是回忆描述...(替换为真实回忆)',
                    image: '/2019-2021/photo2.JPG',
                },
            },
            {
                id: 3,
                x: 75,
                y: 35,
                emoji: '🌸',
                memory: {
                    id: 3,
                    year: '2020',
                    title: '回忆标题3',
                    description: '这里是回忆描述...(替换为真实回忆)',
                    image: '/2019-2021/photo3.JPG',
                },
            },
            {
                id: 4,
                x: 25,
                y: 60,
                emoji: '☕',
                memory: {
                    id: 4,
                    year: '2020',
                    title: '回忆标题4',
                    description: '这里是回忆描述...(替换为真实回忆)',
                    image: '/2019-2021/photo4.JPG',
                },
            },
            {
                id: 5,
                x: 55,
                y: 65,
                emoji: '🎵',
                memory: {
                    id: 5,
                    year: '2021',
                    title: '回忆标题5',
                    description: '这里是回忆描述...(替换为真实回忆)',
                    image: '/2019-2021/photo5.JPG',
                },
            },
            {
                id: 6,
                x: 85,
                y: 70,
                emoji: '🎁',
                memory: {
                    id: 6,
                    year: '2021',
                    title: '回忆标题6',
                    description: '这里是回忆描述...(替换为真实回忆)',
                    image: '/2019-2021/photo6.JPG',
                },
            },
        ],
    },
    {
        id: 2,
        title: '2021-2024 · 思念与成长',
        background: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
        items: [
            {
                id: 7,
                x: 20,
                y: 28,
                emoji: '🎂',
                memory: {
                    id: 7,
                    year: '2021',
                    title: '回忆标题7',
                    description: '这里是回忆描述...(替换为真实回忆)',
                    image: '/2021-2025/photo1.JPG',
                },
            },
            {
                id: 8,
                x: 50,
                y: 33,
                emoji: '✈️',
                memory: {
                    id: 8,
                    year: '2022',
                    title: '回忆标题8',
                    description: '这里是回忆描述...(替换为真实回忆)',
                    image: '/2021-2025/photo2.JPG',
                },
            },
            {
                id: 9,
                x: 80,
                y: 38,
                emoji: '📷',
                memory: {
                    id: 9,
                    year: '2022',
                    title: '回忆标题9',
                    description: '这里是回忆描述...(替换为真实回忆)',
                    image: '/2021-2025/photo3.JPG',
                },
            },
            {
                id: 10,
                x: 30,
                y: 63,
                emoji: '🌟',
                memory: {
                    id: 10,
                    year: '2023',
                    title: '回忆标题10',
                    description: '这里是回忆描述...(替换为真实回忆)',
                    image: '/2021-2025/photo4.JPG',
                },
            },
            {
                id: 11,
                x: 60,
                y: 68,
                emoji: '💌',
                memory: {
                    id: 11,
                    year: '2023',
                    title: '回忆标题11',
                    description: '这里是回忆描述...(替换为真实回忆)',
                    image: '/2021-2025/photo5.JPG',
                },
            },
            {
                id: 12,
                x: 90,
                y: 73,
                emoji: '🎉',
                memory: {
                    id: 12,
                    year: '2024',
                    title: '回忆标题12',
                    description: '这里是回忆描述...(替换为真实回忆)',
                    image: '/2021-2025/photo6.JPG',
                },
            },
        ],
    },
    {
        id: 3,
        title: '2025-永远 · 一直相伴',
        background: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
        items: [
            {
                id: 13,
                x: 18,
                y: 27,
                emoji: '🏠',
                memory: {
                    id: 13,
                    year: '2024',
                    title: '回忆标题13',
                    description: '这里是回忆描述...(替换为真实回忆)',
                    image: '/2025/photo1.JPG',
                },
            },
            {
                id: 14,
                x: 48,
                y: 32,
                emoji: '💍',
                memory: {
                    id: 14,
                    year: '2024',
                    title: '回忆标题14',
                    description: '这里是回忆描述...(替换为真实回忆)',
                    image: '/2025/photo2.JPG',
                },
            },
            {
                id: 15,
                x: 78,
                y: 37,
                emoji: '🌹',
                memory: {
                    id: 15,
                    year: '2025',
                    title: '回忆标题15',
                    description: '这里是回忆描述...(替换为真实回忆)',
                    image: '/2025/photo3.JPG',
                },
            },
            {
                id: 16,
                x: 28,
                y: 62,
                emoji: '🎈',
                memory: {
                    id: 16,
                    year: '2025',
                    title: '回忆标题16',
                    description: '这里是回忆描述...(替换为真实回忆)',
                    image: '/2025/photo4.JPG',
                },
            },
            {
                id: 17,
                x: 58,
                y: 67,
                emoji: '🌈',
                memory: {
                    id: 17,
                    year: '2025',
                    title: '回忆标题17',
                    description: '这里是回忆描述...(替换为真实回忆)',
                    image: '/2025/photo5.JPG',
                },
            },
            {
                id: 18,
                x: 88,
                y: 72,
                emoji: '💖',
                memory: {
                    id: 18,
                    year: '永远',
                    title: '回忆标题18',
                    description: '这里是回忆描述...(替换为真实回忆)',
                    image: '/2025/photo6.JPG',
                },
            },
        ],
    },
];
